AllCops:
  NewCops: enable
  Exclude:
    - bin/*
    - db/schema.rb
    - db/migrate/*
    - db/seeds.rb
    - vendor/**/*
  SuggestExtensions: false

Layout/LineLength:
  AutoCorrect: true
  Max: 120
Metrics/AbcSize:
  Max: 30
Metrics/MethodLength:
  Exclude:
    - 'test/**/*'
  CountAsOne: ['array', 'hash', 'heredoc']
  Max: 20
Metrics/BlockLength:
  Max: 30
Style/Documentation:
  Enabled: false
Style/FrozenStringLiteralComment:
  Enabled: false
Style/StringLiterals:
  EnforcedStyle: double_quotes
Style/StringLiteralsInInterpolation:
  Enabled: false
